# Generated by Django 3.1.6 on 2021-03-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigoro_web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
