# Generated by Django 3.1.6 on 2021-03-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigoro_web_app', '0002_auto_20210318_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('headline', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='news_images')),
                ('body', models.CharField(max_length=5000)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
