# Generated by Django 3.1.6 on 2021-03-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigoro_web_app', '0003_news_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_updates',
            name='author',
            field=models.CharField(default='null', max_length=50, null=True),
        ),
    ]
