# Generated by Django 3.1.6 on 2021-03-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigoro_web_app', '0005_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events',
            new_name='events_model',
        ),
    ]
