# Generated by Django 3.1.6 on 2021-03-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigoro_web_app', '0006_auto_20210328_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_model',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
