# Generated by Django 3.1.6 on 2021-03-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigoro_web_app', '0007_events_model_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_model',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
