# Generated by Django 3.1.6 on 2021-04-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigoro_web_app', '0008_auto_20210329_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_updates',
            name='body',
            field=models.TextField(),
        ),
    ]
