# Generated by Django 3.1.6 on 2021-04-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigoro_web_app', '0009_auto_20210409_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notices',
            name='size',
        ),
        migrations.AlterField(
            model_name='notices',
            name='description',
            field=models.TextField(),
        ),
    ]
